"""Vera bootstrap and per-customer client factory.

Each mock customer in the simulator is a separate Vera org. This module:
  1. Registers each customer's org against Vera production (idempotent —
     reuses an existing key if `.env.local` already has one for the slug).
  2. Hands out a configured `VeraClient` for a given customer slug.

The mapping of slug → display name lives in `CUSTOMERS`. To add a new mock
customer, append a row and re-run `python -m simulator.scripts.bootstrap_orgs`.
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

import httpx
from dotenv import load_dotenv

from vera import VeraClient


REPO_ROOT = Path(__file__).resolve().parents[2]
SIM_ROOT = Path(__file__).resolve().parents[1]
ENV_LOCAL = SIM_ROOT / ".env.local"


@dataclass(frozen=True)
class CustomerSpec:
    slug: str
    display_name: str
    use_case: str
    description: str


CUSTOMERS: dict[str, CustomerSpec] = {
    "scribemd": CustomerSpec(
        slug="scribemd",
        display_name="ScribeMD Health",
        use_case="UC-1: AI scribe → chart entry",
        description="AI scribe vendor for hospitals (Abridge/Ambience-style).",
    ),
    "triageguard": CustomerSpec(
        slug="triageguard",
        display_name="TriageGuard",
        use_case="UC-3: AI triage / symptom checker",
        description="Telehealth front-door (K Health/Amwell-style).",
    ),
    "authassist": CustomerSpec(
        slug="authassist",
        display_name="AuthAssist RCM",
        use_case="UC-2: Prior authorization agent",
        description="Prior auth automation for health systems (Cohere-style).",
    ),
}


# ── env helpers ─────────────────────────────────────────────────────────────


def _load_env() -> None:
    """Load .env.local first (per-customer keys), then .env (defaults)."""
    if ENV_LOCAL.exists():
        load_dotenv(ENV_LOCAL, override=False)
    default_env = SIM_ROOT / ".env"
    if default_env.exists():
        load_dotenv(default_env, override=False)


def _key_var(slug: str) -> str:
    return f"VERA_API_KEY_{slug.upper()}"


def _vera_url() -> str:
    _load_env()
    return os.environ.get("VERA_API_URL", "https://api.usevera.xyz").rstrip("/")


def get_api_key(slug: str) -> Optional[str]:
    _load_env()
    return os.environ.get(_key_var(slug))


# ── registration ────────────────────────────────────────────────────────────


def register_org(spec: CustomerSpec, api_url: Optional[str] = None) -> str:
    """Register a Vera org for this mock customer and return the raw API key.

    Idempotent at the env-var level: if `VERA_API_KEY_<SLUG>` already exists,
    no registration call is made and the existing key is returned. Vera's
    `/v1/register` endpoint itself is not idempotent (calling it twice creates
    two orgs), so we gate at the simulator level.
    """
    existing = get_api_key(spec.slug)
    if existing:
        return existing

    url = (api_url or _vera_url()) + "/v1/register"
    payload = {"org_name": spec.display_name}
    resp = httpx.post(url, json=payload, timeout=30.0)
    resp.raise_for_status()
    data = resp.json()
    return data["api_key"]


def write_key_to_env_local(slug: str, raw_key: str) -> None:
    """Append or update `VERA_API_KEY_<SLUG>=...` in .env.local."""
    var = _key_var(slug)
    line = f"{var}={raw_key}"

    if not ENV_LOCAL.exists():
        ENV_LOCAL.write_text(
            "# Auto-generated by simulator/scripts/bootstrap_orgs.py — do not commit.\n"
            f"{line}\n"
        )
        return

    lines = ENV_LOCAL.read_text().splitlines()
    replaced = False
    for i, l in enumerate(lines):
        if l.startswith(f"{var}="):
            lines[i] = line
            replaced = True
            break
    if not replaced:
        lines.append(line)
    ENV_LOCAL.write_text("\n".join(lines) + "\n")


# ── client factory ──────────────────────────────────────────────────────────


def get_client(
    slug: str,
    *,
    agent_name: str,
    model_id: Optional[str] = None,
    framework: Optional[str] = None,
) -> VeraClient:
    """Return a Vera client configured for this mock customer.

    Raises if the customer hasn't been bootstrapped — run
    `python -m simulator.scripts.bootstrap_orgs` first.
    """
    if slug not in CUSTOMERS:
        raise KeyError(f"Unknown customer slug: {slug!r}. Known: {list(CUSTOMERS)}")
    api_key = get_api_key(slug)
    if not api_key:
        raise RuntimeError(
            f"No API key for {slug!r} in .env.local — run "
            "`python -m simulator.scripts.bootstrap_orgs` to register the org."
        )
    return VeraClient(
        api_url=_vera_url(),
        api_key=api_key,
        agent_name=agent_name,
        model_id=model_id,
        framework=framework,
    )
