"use client";

/**
 * AuditPdfHistory — Phase 4 Wave 2 PR C4.
 *
 * "Generated audit PDFs" history table on the Customer detail page.
 * Backed by ``GET /v1/customers/{customer_id}/audit-pdfs`` (paginated,
 * newest first) and ``POST .../regenerate`` (re-render on click).
 *
 * Storage decision (v1): the backend does NOT persist rendered PDF
 * bytes — re-download regenerates from the persisted ``(date_from,
 * date_to, sections, branding)`` tuple. That means each Re-download
 * incurs the same 5-30s render budget as the original Generate.
 *
 * Single surface — no Compliance roll-up by v1 design decision.
 * The Generate button itself lives in the Customer detail header
 * (C3-scaffold) so this section has NO CTA in its empty state.
 *
 * States
 * ======
 * - loading  → skeleton rows (six rows × column widths)
 * - error    → inline error banner with retry hint
 * - empty    → flat copy line, no CTA
 * - loaded   → table + "Load more" button when total > items.length
 *
 * Columns
 * =======
 *   Generated  |  Generated by  |  Date range  |  Sections  |  Branding
 *              |  Size          |  (re-download)
 *
 * Per CLAUDE.md voice rules:
 *   - "Customer" (not "Tenant") in copy
 *   - Full date with year ("Mar 15, 2026" — never "Mar 15")
 *   - Comma-separated bytes ("12,500")
 *   - tabular-nums on every rendered number
 *   - "Consider…" / "Recommended:" only (no bare imperatives) — N/A here
 */

import * as React from "react";

import { Loading } from "@/components/ui/loading";
import { Skeleton } from "@/components/ui/skeleton";
import {
  ApiError,
  AUDIT_PDF_SECTION_KEYS,
  type AuditPdfHistoryItem,
  type GeneratedBy,
  readAuditPdfErrorCode,
  regenerateAuditPdf,
} from "@/lib/api-client";
import { useAuditPdfHistory } from "@/hooks/use-customers";

const PAGE_SIZE = 20;
const TOTAL_SECTION_COUNT = AUDIT_PDF_SECTION_KEYS.length; // 8

interface AuditPdfHistoryProps {
  /** Customer **primary key** (UUID). Not the tenant_id slug. */
  customer_id: string;
}

export function AuditPdfHistory({ customer_id }: AuditPdfHistoryProps) {
  const [pageCount, setPageCount] = React.useState(1);
  const limit = pageCount * PAGE_SIZE;

  const { data, isLoading, isError, error } = useAuditPdfHistory(
    customer_id,
    { limit, offset: 0 },
    !!customer_id,
  );

  // Per-row regenerate state. We track the in-flight pdf id and any
  // last-error code per row so the inline banner can render alongside
  // the table without disrupting other rows.
  const [regeneratingId, setRegeneratingId] = React.useState<string | null>(
    null,
  );
  const [rowErrorById, setRowErrorById] = React.useState<
    Record<string, string | null>
  >({});

  const onRegenerate = React.useCallback(
    async (item: AuditPdfHistoryItem) => {
      if (regeneratingId) return;
      setRegeneratingId(item.id);
      setRowErrorById((prev) => ({ ...prev, [item.id]: null }));
      try {
        await regenerateAuditPdf(customer_id, item.id);
      } catch (e) {
        const code = readAuditPdfErrorCode(e);
        const message = mapRegenerateErrorMessage(code, e);
        setRowErrorById((prev) => ({ ...prev, [item.id]: message }));
      } finally {
        setRegeneratingId(null);
      }
    },
    [customer_id, regeneratingId],
  );

  return (
    <section
      className="space-y-3"
      data-testid="audit-pdf-history"
      aria-labelledby="audit-pdf-history-heading"
    >
      <h2
        id="audit-pdf-history-heading"
        className="text-[11px] font-semibold uppercase tracking-[0.08em] text-[color:var(--ink-2)]"
      >
        Audit PDFs
      </h2>

      {isLoading ? (
        <AuditPdfHistorySkeleton />
      ) : isError ? (
        <ErrorBanner message={error?.message ?? null} />
      ) : !data || data.items.length === 0 ? (
        <EmptyRow />
      ) : (
        <HistoryTable
          items={data.items}
          total={data.total}
          onRegenerate={onRegenerate}
          regeneratingId={regeneratingId}
          rowErrorById={rowErrorById}
          onLoadMore={
            data.items.length < data.total
              ? () => setPageCount((c) => c + 1)
              : null
          }
        />
      )}
    </section>
  );
}

// ── States ─────────────────────────────────────────────────────────────

function AuditPdfHistorySkeleton() {
  return (
    <div
      className="space-y-2 rounded-md border border-[color:var(--ink-4)] bg-[color:var(--paper)] p-3"
      aria-busy="true"
      data-testid="audit-pdf-history-loading"
    >
      {Array.from({ length: 4 }).map((_, i) => (
        <div key={i} className="flex items-center gap-4">
          <Skeleton className="h-4 w-32" />
          <Skeleton className="h-4 w-28" />
          <Skeleton className="h-4 w-40" />
          <Skeleton className="h-4 w-20" />
          <Skeleton className="h-4 w-24" />
          <Skeleton className="h-4 w-16" />
        </div>
      ))}
    </div>
  );
}

function ErrorBanner({ message }: { message: string | null }) {
  return (
    <div
      role="alert"
      className="rounded-md border border-[color:var(--brick)]/30 bg-[color:var(--brick-bg)] px-4 py-3 text-[13px] text-[color:var(--ink)]"
      data-testid="audit-pdf-history-error"
    >
      <p className="font-medium">Audit PDF history could not be loaded.</p>
      <p className="mt-1 text-[12px] text-[color:var(--ink-2)]">
        {message ??
          "Refresh the page. If the problem persists, contact support."}
      </p>
    </div>
  );
}

function EmptyRow() {
  return (
    <p
      className="rounded-md border border-dashed border-[color:var(--ink-4)] bg-[color:var(--paper-2)] px-4 py-6 text-[13px] text-[color:var(--ink-2)]"
      data-testid="audit-pdf-history-empty"
    >
      No audit PDFs generated yet for this Customer.
    </p>
  );
}

// ── Table ──────────────────────────────────────────────────────────────

interface HistoryTableProps {
  items: AuditPdfHistoryItem[];
  total: number;
  onRegenerate: (item: AuditPdfHistoryItem) => void;
  regeneratingId: string | null;
  rowErrorById: Record<string, string | null>;
  onLoadMore: (() => void) | null;
}

function HistoryTable({
  items,
  total,
  onRegenerate,
  regeneratingId,
  rowErrorById,
  onLoadMore,
}: HistoryTableProps) {
  return (
    <div
      className="overflow-x-auto rounded-md border border-[color:var(--ink-4)] bg-[color:var(--paper)]"
      data-testid="audit-pdf-history-loaded"
    >
      <table className="min-w-full text-[13px] text-[color:var(--ink)]">
        <thead className="bg-[color:var(--paper-2)] text-left text-[11px] font-medium uppercase tracking-[0.06em] text-[color:var(--ink-2)]">
          <tr>
            <th scope="col" className="px-4 py-2.5 font-medium">
              Generated
            </th>
            <th scope="col" className="px-4 py-2.5 font-medium">
              Generated by
            </th>
            <th scope="col" className="px-4 py-2.5 font-medium">
              Date range
            </th>
            <th scope="col" className="px-4 py-2.5 font-medium">
              Sections
            </th>
            <th scope="col" className="px-4 py-2.5 font-medium">
              Branding
            </th>
            <th scope="col" className="px-4 py-2.5 text-right font-medium">
              Size
            </th>
            <th scope="col" className="px-4 py-2.5 font-medium">
              <span className="sr-only">Re-download</span>
            </th>
          </tr>
        </thead>
        <tbody className="divide-y divide-[color:var(--ink-4)]">
          {items.map((item) => (
            <HistoryRow
              key={item.id}
              item={item}
              onRegenerate={onRegenerate}
              regenerating={regeneratingId === item.id}
              disabled={regeneratingId !== null && regeneratingId !== item.id}
              errorMessage={rowErrorById[item.id] ?? null}
            />
          ))}
        </tbody>
      </table>
      <div className="flex items-center justify-between gap-4 border-t border-[color:var(--ink-4)] bg-[color:var(--paper-2)] px-4 py-2.5">
        <p className="text-[12px] tabular-nums text-[color:var(--ink-3)]">
          Showing {items.length.toLocaleString()} of {total.toLocaleString()}{" "}
          generated audit PDF
          {total === 1 ? "" : "s"}
        </p>
        {onLoadMore ? (
          <button
            type="button"
            onClick={onLoadMore}
            className="inline-flex h-8 items-center justify-center rounded-[10px] border border-[color:var(--ink-4)] px-3 text-[12px] font-medium text-[color:var(--ink)] transition-colors hover:bg-[color:var(--paper-3)] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[color:var(--ink)]"
            data-testid="audit-pdf-history-load-more"
          >
            Load more
          </button>
        ) : null}
      </div>
    </div>
  );
}

interface HistoryRowProps {
  item: AuditPdfHistoryItem;
  onRegenerate: (item: AuditPdfHistoryItem) => void;
  regenerating: boolean;
  disabled: boolean;
  errorMessage: string | null;
}

function HistoryRow({
  item,
  onRegenerate,
  regenerating,
  disabled,
  errorMessage,
}: HistoryRowProps) {
  const generatedLabel = formatGeneratedAt(item.generated_at);
  const dateRangeLabel = formatDateRange(item.date_from, item.date_to);
  const sectionsLabel = formatSectionsLabel(item.sections);
  const brandingLabel = formatBrandingLabel(item.branding);
  const sizeLabel = formatBytes(item.byte_size);
  const generatedByLabel = formatGeneratedBy(item.generated_by);

  return (
    <>
      <tr data-testid={`audit-pdf-history-row-${item.id}`}>
        <td className="px-4 py-2.5 tabular-nums text-[color:var(--ink)]">
          {generatedLabel}
        </td>
        <td className="px-4 py-2.5 text-[color:var(--ink-2)]">
          {generatedByLabel}
        </td>
        <td className="px-4 py-2.5 tabular-nums text-[color:var(--ink-2)]">
          {dateRangeLabel}
        </td>
        <td className="px-4 py-2.5 text-[color:var(--ink-2)]">
          <span title={sectionsTooltip(item.sections)}>{sectionsLabel}</span>
        </td>
        <td className="px-4 py-2.5 text-[color:var(--ink-2)]">
          {brandingLabel}
        </td>
        <td className="px-4 py-2.5 text-right tabular-nums text-[color:var(--ink-2)]">
          {sizeLabel}
        </td>
        <td className="px-4 py-2.5 text-right">
          <button
            type="button"
            onClick={() => onRegenerate(item)}
            disabled={regenerating || disabled}
            className="inline-flex h-8 items-center justify-center gap-1 rounded-[10px] border border-[color:var(--ink-4)] px-3 text-[12px] font-medium text-[color:var(--ink)] transition-colors hover:bg-[color:var(--paper-2)] focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[color:var(--ink)] disabled:cursor-not-allowed disabled:opacity-50"
            data-testid={`audit-pdf-history-regenerate-${item.id}`}
          >
            {regenerating ? (
              <>
                <Loading.Spinner
                  size={12}
                  label="Re-downloading audit PDF"
                  className="text-[color:var(--ink-2)]"
                />
                <span>Re-downloading…</span>
              </>
            ) : (
              <span>Re-download</span>
            )}
          </button>
        </td>
      </tr>
      {errorMessage ? (
        <tr>
          <td colSpan={7} className="px-4 pb-2.5">
            <div
              role="alert"
              className="rounded-md border border-[color:var(--brick)]/30 bg-[color:var(--brick-bg)] px-3 py-2 text-[12px] text-[color:var(--ink)]"
              data-testid={`audit-pdf-history-row-error-${item.id}`}
            >
              {errorMessage}
            </div>
          </td>
        </tr>
      ) : null}
    </>
  );
}

// ── Formatters (exported for the test file to pin the contract) ────────

const MONTHS = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec",
] as const;

function parseIsoUtc(iso: string): Date | null {
  if (!iso) return null;
  // Tolerate both ``...Z`` and ``...+00:00`` — Date() handles both.
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return null;
  return d;
}

/**
 * Format an ISO 8601 UTC timestamp as ``"Mar 15, 2026 · 14:02 UTC"``.
 * Per CLAUDE.md voice rules: full date with year, tabular-nums on the
 * caller side, explicit UTC suffix so a US-EST operator never confuses
 * a generated_at for local time.
 */
export function formatGeneratedAt(iso: string): string {
  const d = parseIsoUtc(iso);
  if (!d) return iso || "—";
  const month = MONTHS[d.getUTCMonth()];
  const day = d.getUTCDate();
  const year = d.getUTCFullYear();
  const hh = String(d.getUTCHours()).padStart(2, "0");
  const mm = String(d.getUTCMinutes()).padStart(2, "0");
  return `${month} ${day}, ${year} · ${hh}:${mm} UTC`;
}

/**
 * Format a single YYYY-MM-DD as ``"Mar 15, 2026"`` (no off-by-one
 * timezone shift — parse as UTC date-only).
 */
function formatIsoDateLong(iso: string): string {
  if (!iso) return "";
  const [yStr, mStr, dStr] = iso.split("-");
  const y = Number(yStr);
  const m = Number(mStr);
  const d = Number(dStr);
  if (!y || !m || !d) return iso;
  return `${MONTHS[m - 1]} ${d}, ${y}`;
}

/**
 * Date range collapsed to one line. Same-month dates render as
 * ``"Mar 1 – Mar 15, 2026"``; cross-month or cross-year render the full
 * ``"Feb 28, 2026 – Mar 5, 2026"`` form.
 */
export function formatDateRange(from: string, to: string): string {
  if (!from || !to) return `${from || "—"} – ${to || "—"}`;
  const [yF, mF] = from.split("-");
  const [yT, mT] = to.split("-");
  // Cross-year OR cross-month → spell both ends in full.
  if (yF !== yT || mF !== mT) {
    return `${formatIsoDateLong(from)} – ${formatIsoDateLong(to)}`;
  }
  // Same month + year — collapse the end-date prefix.
  const month = MONTHS[Number(mF) - 1] ?? "";
  const dF = Number(from.slice(8, 10));
  const dT = Number(to.slice(8, 10));
  const y = Number(yF);
  if (!month || !dF || !dT || !y) {
    return `${formatIsoDateLong(from)} – ${formatIsoDateLong(to)}`;
  }
  return `${month} ${dF} – ${month} ${dT}, ${y}`;
}

/**
 * "All" if every section is present, otherwise "N sections". The
 * tooltip surfaces the comma-separated section keys regardless.
 */
export function formatSectionsLabel(sections: string[]): string {
  const n = sections.length;
  if (n === 0) return "—";
  if (n >= TOTAL_SECTION_COUNT) return "All";
  return `${n} section${n === 1 ? "" : "s"}`;
}

function sectionsTooltip(sections: string[]): string {
  return sections.length ? sections.join(", ") : "";
}

/**
 * "customer" → "Customer", "vera-neutral" → "Vera-neutral". Defensive
 * for unknown branding values so a historical row with a deprecated
 * branding string still renders a readable label.
 */
export function formatBrandingLabel(branding: string): string {
  if (branding === "customer") return "Customer";
  if (branding === "vera-neutral") return "Vera-neutral";
  // Title-case fallback for unknowns.
  return branding ? branding.charAt(0).toUpperCase() + branding.slice(1) : "—";
}

/**
 * Render bytes with comma-separated thousands. Switches to KB above 100
 * KB and MB above 100 MB so the column stays narrow on a busy customer.
 * Always tabular-nums on the caller side. Per CLAUDE.md: no abbreviation
 * under 10K, so anything under 100 KB renders as raw bytes.
 */
export function formatBytes(bytes: number): string {
  if (!Number.isFinite(bytes) || bytes < 0) return "—";
  if (bytes < 100 * 1024) {
    // copy-allow: pure formatter — callers wrap the returned string in
    // a tabular-nums className at the render site (HistoryRow Size cell).
    return `${Math.round(bytes).toLocaleString()} B`;
  }
  if (bytes < 100 * 1024 * 1024) {
    const kb = bytes / 1024;
    return `${kb.toLocaleString(undefined, {
      maximumFractionDigits: 1,
    })} KB`;
  }
  const mb = bytes / (1024 * 1024);
  return `${mb.toLocaleString(undefined, {
    maximumFractionDigits: 1,
  })} MB`;
}

/**
 * Pretty-print the ``generated_by`` envelope. Prefers a resolved label
 * (Clerk email / API key name) and falls back to the raw id; "—" if
 * the field is null (the C4 backend writes NULL when a customer-Clerk
 * session triggered the render — see route docstring).
 */
export function formatGeneratedBy(generated_by: GeneratedBy | null): string {
  if (!generated_by) return "—";
  if (generated_by.api_key_name) {
    return `${generated_by.api_key_name} (API key)`;
  }
  if (generated_by.api_key_id) {
    return `API key ${generated_by.api_key_id.slice(0, 8)}…`;
  }
  if (generated_by.user_email_or_name) {
    return generated_by.user_email_or_name;
  }
  if (generated_by.user_id) {
    return generated_by.user_id;
  }
  return "—";
}

/**
 * Map a regenerate ApiError code → inline banner copy. Exported so the
 * test file can pin the contract.
 */
export function mapRegenerateErrorMessage(
  code: string | null,
  err: unknown,
): string {
  if (code === "baa_expired") {
    return "BAA expired — renew on Settings › BAA Management before re-downloading this audit PDF.";
  }
  if (code === "pdf_render_timeout") {
    return "Re-download timed out — retry in a moment.";
  }
  if (err instanceof ApiError && err.status === 404) {
    return "This audit PDF history row could not be found. It may have been removed.";
  }
  return "Failed to re-download audit PDF.";
}
